import subprocess

variants = ["go", "rust"]
variants_file = {}
for variant in variants:
    subprocess.run(f"./generate_directory_{variant}", shell=True)
    variants_file[variant] = open("index.html", "r").read()

for i in range(1, len(variants)):
    if variants_file[variants[i]] != variants_file[variants[i-1]]:
        print(f"mismatch in directory file generated by {variants[i]}")
        exit(1)