name: Update Directory
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  update-directory:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Executable
        id: executable-cache
        uses: actions/cache@v2
        with:
          path: generate_directory
          key: executable-${{ hashFiles('ci/ci-go/generate_directory.go') }}-${{ hashFiles('ci/ci-go/go.mod') }}
      - name: Build Executable
        if: steps.executable-cache.outputs.cache-hit != 'true'
        run: cd ci/ci-go && go build generate_directory.go && mv generate_directory ../../ && cd ../../
      - name: Run Executable
        run: ./generate_directory
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1