name: Update Directory
on: [push]
jobs:
  update-directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go run ci/generate_directory.go
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated: update directory"