name: Update Directory
on: [push]
jobs:
  update-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Executable
        id: executable-cache
        uses: actions/cache@v2
        with:
          path: generate_directory
          key: executable-${{ hashFiles('ci/generate_directory.go') }}-${{ hashFiles('go.mod') }}
      - name: Build Executable
        if: steps.executable-cache.outputs.cache-hit != 'true'
        run: go build ci/generate_directory.go
      - name: Run Executable
        run: ./generate_directory
      - run: rm generate_directory
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated: update directory"