name: Update Directory
on: [push]
jobs:
  update-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Executable
        id: executable-cache
        uses: actions/cache@v2
        with:
          path: generate_directory
          key: executable-${{ hashFiles('ci/generate_directory.go') }}-${{ hashFiles('go.mod') }}
      - name: Build Executable
        if: steps.executable-cache.outputs.cache-hit != 'true'
        run: go build ci/generate_directory.go
      - name: Run Executable
        run: ./generate_directory
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy Pages
        uses: actions/deploy-pages@v1